In [6]:

!pip install numpy



     ---------------------------------------- 15.9/15.9 MB 4.8 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\pc-1\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [7]:
# 1. Quyidagi massivni NumPy yordamida yarating va elementlarga indeks orqali murojaat qiling.
# numpy.array() yordamida A massivini yarating.
# 1-qator, 2-ustundagi elementni chop eting.
import numpy as np

a = np.array([[3, 7, 2],
              [4, 6, 1]])
number = a[0,1]
print(number)

7


In [39]:
# Oxirgi ustunning barcha elementlarini chiqaring.
a = np.array([[3, 7, 2],
              [4, 6, 1]])
print(a[1])


[4 6 1]


In [26]:
# 2.Tasodifiy massiv yaratish (random())
# 5×5 o‘lchamli tasodifiy sonlardan iborat massiv hosil qiling.
a = np.random.randn()
print(a, '\n')

b = np.random.randn(5,5)
print(b)


-0.2893555699221995 

[[ 0.49354786  1.37472688  0.64756691  0.08664232  0.99022522]
 [-1.47178445  0.68689899  0.21219931  1.61588603 -0.67083712]
 [ 0.00339677  0.01855106  1.15007634 -0.20895443 -0.2184135 ]
 [-0.84212205 -1.33127302 -0.10312945  0.11516873  1.04276186]
 [-0.73282894 -0.30931783  0.59121647  0.91692445  0.85696175]]


In [24]:
# numpy.random.randint(1, 100, (5,5)) yordamida 5x5 o‘lchamli tasodifiy butun sonli massiv yarating.
# Massivning 3-qatorini chop eting.
# Eng katta va eng kichik elementlarini toping.

a =np.random.randint(1, 100, (5,5))
print(a, '\n')

line = a[2]
print(line, '\n')

print(f'Katta elementlari: {np.max(a)}')
print(f'Kichik elementlari: {np.min(a)}')

[[15 65  7 48 76]
 [ 2 49 32 54 92]
 [41 52  4 25 72]
 [69 14 19 48 41]
 [25 40 52 24 33]] 

[41 52  4 25 72] 

Katta elementlari: 92
Kichik elementlari: 2


In [33]:
# 3.for bilan massivni tahlil qilish
# b =  ([[5, 8, 9],
#       [4, 6, 1]])
# numpy.array() yordamida B massivini yarating.
# For sikli yordamida har bir elementni ekranga chiqaring.
# Har bir qatorni alohida chiqaring.
b = np.array([[5, 8, 9],
              [4, 6, 1]])
for row in b:
    print(row, '\n')

for row in b:
    for element in row:
        print(element)


[5 8 9] 

[4 6 1] 

5
8
9
4
6
1


In [43]:
# 4. .shape bilan o‘lchamni aniqlash
# c =  ([[5, 8, 9],
#       [4, 6, 1]])
# numpy.array() yordamida C massivini yarating.
# .shape funksiyasidan foydalanib, massiv o‘lchamini chop eting.
# Massivning 1-qavati va 2-qavati elementlarini chiqaring.
c = np.array([[5, 8, 9],
              [4, 6, 1]])
print(c.shape)

qavat = c[:,0]
print(qavat)


(2, 3)
[5 4]


In [49]:
# 5. Massivlarni qo‘shish (+)
# D =  ([[5, 8, 9],   E =  ([[9, 2, 4],
#       [2, 7, 6]]) 	   [7, 2, 3]])
# D va E massivlarini NumPy yordamida yarating.
# D + E amalini bajaring va natijani chiqaring.
# Natijaviy massivning 2-qatorini chop eting.

D = np.array([[5, 8, 9],
      [2, 7, 6]])
E = np.array([[9, 2, 4],
       [7, 2, 3]])

sum_de = D + E
print(sum_de, '\n')

print('2-qator:', sum_de[1])

[[14 10 13]
 [ 9  9  9]] 

2-qator: [9 9 9]


In [52]:
# 6. Ikki o‘lchamli massivdan ma’lum qismini ajratib olish
# Quyidagi 4×4 tasodifiy massivdan 3×3 kichik massivni ajrating.
# numpy.random.randint(10, 50, (4,4)) yordamida 4x4 tasodifiy massiv yarating.
# Ushbu massivning 3x3 qismni (faqat 1–3-qator va 1–3-ustun) ajratib oling.
# Natijani ekranga chiqaring.

a =np.random.randint(10, 50, (4,4))
print(a, '\n')
b = a[0:3, 0:3]
print(b)


[[10 44 15 11]
 [29 22 28 48]
 [30 30 28 34]
 [11 46 34 29]] 

[[10 44 15]
 [29 22 28]
 [30 30 28]]


In [53]:
# 7. Matematika: 2ta masssivning o‘rta arifmetigini hisoblash
# F =  ([[1, 2, 4],   G =  ([[5, 6, 2],
#       [6, 4, 3]]) 	   [5, 8, 1]])
# F va G massivlarini yarating.
# Ushbu massivlarning o‘rta arifmetigini (ya’ni (F + G) / 2) hisoblang.
# Natijaviy massivni ekranga chiqaring.
F = np.array([[1, 2, 4],
       [6, 4, 3]])
G = np.array([[5, 6, 2],
       [5, 8, 1]])

avg_massiv = ((F+G)/2)
print(avg_massiv)


[[3.  4.  3. ]
 [5.5 6.  2. ]]
